resolver: lts-9.13
packages:
- .
- location: ..
  extra-dep: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
